// <auto-generated />
using System;
using BedAndDrinks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedAndDrinks.Migrations
{
    [DbContext(typeof(BedAndDrinkContext))]
    [Migration("20250313182339_AgregarCampoFechaCreacion")]
    partial class AgregarCampoFechaCreacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BedAndDrinks.Models.Habitacion", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("idHabitacion");

                    b.HasKey("IdHabitacion")
                        .HasName("PK__Habitaci__D9D53BE2EA163241");

                    b.ToTable("Habitacion", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.Huespede", b =>
                {
                    b.Property<int>("IdHuesped")
                        .HasColumnType("int")
                        .HasColumnName("idHuesped");

                    b.Property<string>("ApellidoHuesped")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("apellidoHuesped");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CorreoElectronicoH")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("correoElectronicoH");

                    b.Property<string>("Departamento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("departamento");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<DateOnly?>("FechaNacimientoH")
                        .HasColumnType("date")
                        .HasColumnName("fechaNacimientoH");

                    b.Property<string>("NombreHuesped")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombreHuesped");

                    b.Property<string>("TelMovil")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("telMovil");

                    b.HasKey("IdHuesped")
                        .HasName("PK__Huespede__4B73CF9709A6CCDF");

                    b.ToTable("Huespedes");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Paquete", b =>
                {
                    b.Property<int>("IdPaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPaquete");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaquete"));

                    b.HasKey("IdPaquete")
                        .HasName("PK__paquetes__646BA35FBD981CD5");

                    b.ToTable("paquetes", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.PaqueteServicio", b =>
                {
                    b.Property<int>("IdPaqueteservicios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPaqueteservicios");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaqueteservicios"));

                    b.Property<int?>("IdPaquetePs")
                        .HasColumnType("int")
                        .HasColumnName("idPaquetePS");

                    b.Property<int?>("IdServicioPs")
                        .HasColumnType("int")
                        .HasColumnName("idServicioPS");

                    b.HasKey("IdPaqueteservicios")
                        .HasName("PK__paqueteS__6DBE89443DF4DAC1");

                    b.HasIndex("IdPaquetePs");

                    b.HasIndex("IdServicioPs");

                    b.ToTable("paqueteServicios", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPermiso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombrePermiso")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombrePermiso");

                    b.HasKey("IdPermiso")
                        .HasName("PK__permisos__06A58486733566DA");

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.PermisosTipoRol", b =>
                {
                    b.Property<int>("IdPtr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPTR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPtr"));

                    b.Property<int?>("IdPermisoPtr")
                        .HasColumnType("int")
                        .HasColumnName("IdPermisoPTR");

                    b.Property<int?>("IdTipoRolPtr")
                        .HasColumnType("int")
                        .HasColumnName("idTipoRolPTR");

                    b.HasKey("IdPtr")
                        .HasName("PK__permisos__3D065EF5A32D5E2E");

                    b.HasIndex("IdPermisoPtr");

                    b.HasIndex("IdTipoRolPtr");

                    b.ToTable("permisosTipoRol", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.Registro", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRegistro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<DateOnly?>("FechaLlegada")
                        .HasColumnType("date")
                        .HasColumnName("fechaLlegada");

                    b.Property<DateOnly?>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("fechaSalida");

                    b.Property<int?>("IdHuespedReg")
                        .HasColumnType("int")
                        .HasColumnName("idHuespedReg");

                    b.Property<int?>("IdReservaReg")
                        .HasColumnType("int")
                        .HasColumnName("idReservaReg");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("valorTotal");

                    b.HasKey("IdRegistro")
                        .HasName("PK__registro__62FC8F58683AED6C");

                    b.HasIndex("IdHuespedReg");

                    b.HasIndex("IdReservaReg");

                    b.ToTable("registros", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idReserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Estado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<DateOnly?>("FechaCaducidad")
                        .HasColumnType("date")
                        .HasColumnName("fechaCaducidad");

                    b.Property<int?>("IdReservaDePaquetesR")
                        .HasColumnType("int")
                        .HasColumnName("idReservaDePaquetesR");

                    b.Property<string>("ObservacionesReserva")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacionesReserva");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reserva__94D104C8466E6303");

                    b.HasIndex("IdReservaDePaquetesR");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaDePaquete", b =>
                {
                    b.Property<int>("IdReservaDePaquetes")
                        .HasColumnType("int")
                        .HasColumnName("idReservaDePaquetes");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdPaqueteRdp")
                        .HasColumnType("int")
                        .HasColumnName("idPaqueteRDP");

                    b.HasKey("IdReservaDePaquetes")
                        .HasName("PK__reservaD__0B271E1EE73DCCFE");

                    b.HasIndex("IdPaqueteRdp");

                    b.ToTable("reservaDePaquetes", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaDeServicio", b =>
                {
                    b.Property<int>("IdReservaServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idReservaServicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReservaServicio"));

                    b.Property<int?>("IdReservaRs")
                        .HasColumnType("int")
                        .HasColumnName("idReservaRS");

                    b.Property<string>("ObservacionRs")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacionRS");

                    b.HasKey("IdReservaServicio")
                        .HasName("PK__ReservaD__6DE53D0407D80932");

                    b.HasIndex("IdReservaRs");

                    b.ToTable("ReservaDeServicios");
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaDss", b =>
                {
                    b.Property<int>("IdreservaDds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idreservaDDS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdreservaDds"));

                    b.Property<int?>("IdReservaServiciosRdss")
                        .HasColumnType("int")
                        .HasColumnName("idReservaServiciosRDSS");

                    b.Property<int?>("IdServicioRdds")
                        .HasColumnType("int")
                        .HasColumnName("idServicioRDDS");

                    b.HasKey("IdreservaDds")
                        .HasName("PK__reservaD__165098225E11E3F7");

                    b.HasIndex("IdReservaServiciosRdss");

                    b.HasIndex("IdServicioRdds");

                    b.ToTable("reservaDSS", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaHabitacion", b =>
                {
                    b.Property<int>("IdReservaHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idReservaHabitacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReservaHabitacion"));

                    b.Property<int?>("IdHabitacionRh")
                        .HasColumnType("int")
                        .HasColumnName("idHabitacionRH");

                    b.Property<int?>("IdReservaRh")
                        .HasColumnType("int")
                        .HasColumnName("idReservaRH");

                    b.HasKey("IdReservaHabitacion")
                        .HasName("PK__ReservaH__EBBB04C1D85D8567");

                    b.HasIndex("IdHabitacionRh");

                    b.HasIndex("IdReservaRh");

                    b.ToTable("ReservaHabitacion", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int?>("IdTipoRolR")
                        .HasColumnType("int")
                        .HasColumnName("idTipoRolR");

                    b.Property<string>("NombreRol")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__3C872F7693706329");

                    b.HasIndex("IdTipoRolR");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idServicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("categoria");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("costo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Disponibilidad")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("disponibilidad");

                    b.Property<string>("Estado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("IdServicio")
                        .HasName("PK__Servicio__CEB981191E26D17D");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("BedAndDrinks.Models.TipoHabitacion", b =>
                {
                    b.Property<int>("IdTipoHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("idTipoHabitacion");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int")
                        .HasColumnName("capacidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdHabitacionTh")
                        .HasColumnType("int")
                        .HasColumnName("idHabitacionTH");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("precio");

                    b.HasKey("IdTipoHabitacion")
                        .HasName("PK__tipoHabi__64CD3F69840A4D5C");

                    b.HasIndex("IdHabitacionTh");

                    b.ToTable("tipoHabitacion", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.TipoHabitacionPaquete", b =>
                {
                    b.Property<int>("IdThp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTHP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThp"));

                    b.Property<int?>("IdPaqueteThp")
                        .HasColumnType("int")
                        .HasColumnName("idPaqueteTHP");

                    b.Property<int?>("IdTipoHabitacionThp")
                        .HasColumnType("int")
                        .HasColumnName("idTipoHabitacionTHP");

                    b.HasKey("IdThp")
                        .HasName("PK__tipoHabi__020E80DF850417C7");

                    b.HasIndex("IdPaqueteThp");

                    b.HasIndex("IdTipoHabitacionThp");

                    b.ToTable("tipoHabitacionPaquetes", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.TipoRol", b =>
                {
                    b.Property<int>("IdTipoRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoRol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoRol"));

                    b.Property<string>("NombreTipoRol")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdTipoRol")
                        .HasName("PK__TipoRol__F81762AA87CF1075");

                    b.ToTable("TipoRol", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("Contrasena")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("CorreoUsuario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("correoUsuario");

                    b.Property<string>("EstadoUsuario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("estadoUsuario");

                    b.Property<int?>("IdReservaU")
                        .HasColumnType("int")
                        .HasColumnName("idReservaU");

                    b.Property<int?>("IdRolUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idRolUsuario");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacion");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__645723A627A2FE78");

                    b.HasIndex("IdReservaU");

                    b.HasIndex("IdRolUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("BedAndDrinks.Models.PaqueteServicio", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Paquete", "IdPaquetePsNavigation")
                        .WithMany("PaqueteServicios")
                        .HasForeignKey("IdPaquetePs")
                        .HasConstraintName("FK__paqueteSe__idPaq__4F7CD00D");

                    b.HasOne("BedAndDrinks.Models.Servicio", "IdServicioPsNavigation")
                        .WithMany("PaqueteServicios")
                        .HasForeignKey("IdServicioPs")
                        .HasConstraintName("FK__paqueteSe__idSer__5070F446");

                    b.Navigation("IdPaquetePsNavigation");

                    b.Navigation("IdServicioPsNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.PermisosTipoRol", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Permiso", "IdPermisoPtrNavigation")
                        .WithMany("PermisosTipoRols")
                        .HasForeignKey("IdPermisoPtr")
                        .HasConstraintName("FK__permisosT__IdPer__45F365D3");

                    b.HasOne("BedAndDrinks.Models.TipoRol", "IdTipoRolPtrNavigation")
                        .WithMany("PermisosTipoRols")
                        .HasForeignKey("IdTipoRolPtr")
                        .HasConstraintName("FK__permisosT__idTip__44FF419A");

                    b.Navigation("IdPermisoPtrNavigation");

                    b.Navigation("IdTipoRolPtrNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Registro", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Huespede", "IdHuespedRegNavigation")
                        .WithMany("Registros")
                        .HasForeignKey("IdHuespedReg")
                        .HasConstraintName("FK__registros__idHue__5629CD9C");

                    b.HasOne("BedAndDrinks.Models.Reserva", "IdReservaRegNavigation")
                        .WithMany("Registros")
                        .HasForeignKey("IdReservaReg")
                        .HasConstraintName("FK__registros__idRes__5535A963");

                    b.Navigation("IdHuespedRegNavigation");

                    b.Navigation("IdReservaRegNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Reserva", b =>
                {
                    b.HasOne("BedAndDrinks.Models.ReservaDePaquete", "IdReservaDePaquetesRNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdReservaDePaquetesR")
                        .HasConstraintName("FK__Reserva__idReser__5441852A");

                    b.Navigation("IdReservaDePaquetesRNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaDePaquete", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Paquete", "IdPaqueteRdpNavigation")
                        .WithMany("ReservaDePaquetes")
                        .HasForeignKey("IdPaqueteRdp")
                        .HasConstraintName("FK__reservaDe__idPaq__534D60F1");

                    b.Navigation("IdPaqueteRdpNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaDeServicio", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Reserva", "IdReservaRsNavigation")
                        .WithMany("ReservaDeServicios")
                        .HasForeignKey("IdReservaRs")
                        .HasConstraintName("FK__ReservaDe__idRes__4E88ABD4");

                    b.Navigation("IdReservaRsNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaDss", b =>
                {
                    b.HasOne("BedAndDrinks.Models.ReservaDeServicio", "IdReservaServiciosRdssNavigation")
                        .WithMany("ReservaDsses")
                        .HasForeignKey("IdReservaServiciosRdss")
                        .HasConstraintName("FK__reservaDS__idRes__4CA06362");

                    b.HasOne("BedAndDrinks.Models.Servicio", "IdServicioRddsNavigation")
                        .WithMany("ReservaDsses")
                        .HasForeignKey("IdServicioRdds")
                        .HasConstraintName("FK__reservaDS__idSer__4D94879B");

                    b.Navigation("IdReservaServiciosRdssNavigation");

                    b.Navigation("IdServicioRddsNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaHabitacion", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Habitacion", "IdHabitacionRhNavigation")
                        .WithMany("ReservaHabitacions")
                        .HasForeignKey("IdHabitacionRh")
                        .HasConstraintName("FK__ReservaHa__idHab__4AB81AF0");

                    b.HasOne("BedAndDrinks.Models.Reserva", "IdReservaRhNavigation")
                        .WithMany("ReservaHabitacions")
                        .HasForeignKey("IdReservaRh")
                        .HasConstraintName("FK__ReservaHa__idRes__49C3F6B7");

                    b.Navigation("IdHabitacionRhNavigation");

                    b.Navigation("IdReservaRhNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Rol", b =>
                {
                    b.HasOne("BedAndDrinks.Models.TipoRol", "IdTipoRolRNavigation")
                        .WithMany("Rols")
                        .HasForeignKey("IdTipoRolR")
                        .HasConstraintName("FK__Rol__idTipoRolR__46E78A0C");

                    b.Navigation("IdTipoRolRNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.TipoHabitacion", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Habitacion", "IdHabitacionThNavigation")
                        .WithMany("TipoHabitacions")
                        .HasForeignKey("IdHabitacionTh")
                        .HasConstraintName("FK__tipoHabit__idHab__4BAC3F29");

                    b.Navigation("IdHabitacionThNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.TipoHabitacionPaquete", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Paquete", "IdPaqueteThpNavigation")
                        .WithMany("TipoHabitacionPaquetes")
                        .HasForeignKey("IdPaqueteThp")
                        .HasConstraintName("FK__tipoHabit__idPaq__5165187F");

                    b.HasOne("BedAndDrinks.Models.TipoHabitacion", "IdTipoHabitacionThpNavigation")
                        .WithMany("TipoHabitacionPaquetes")
                        .HasForeignKey("IdTipoHabitacionThp")
                        .HasConstraintName("FK__tipoHabit__idTip__52593CB8");

                    b.Navigation("IdPaqueteThpNavigation");

                    b.Navigation("IdTipoHabitacionThpNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Usuario", b =>
                {
                    b.HasOne("BedAndDrinks.Models.Reserva", "IdReservaUNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdReservaU")
                        .HasConstraintName("FK__Usuario__idReser__48CFD27E");

                    b.HasOne("BedAndDrinks.Models.Rol", "IdRolUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRolUsuario")
                        .HasConstraintName("FK__Usuario__idRolUs__47DBAE45");

                    b.Navigation("IdReservaUNavigation");

                    b.Navigation("IdRolUsuarioNavigation");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Habitacion", b =>
                {
                    b.Navigation("ReservaHabitacions");

                    b.Navigation("TipoHabitacions");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Huespede", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Paquete", b =>
                {
                    b.Navigation("PaqueteServicios");

                    b.Navigation("ReservaDePaquetes");

                    b.Navigation("TipoHabitacionPaquetes");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Permiso", b =>
                {
                    b.Navigation("PermisosTipoRols");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Reserva", b =>
                {
                    b.Navigation("Registros");

                    b.Navigation("ReservaDeServicios");

                    b.Navigation("ReservaHabitacions");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaDePaquete", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BedAndDrinks.Models.ReservaDeServicio", b =>
                {
                    b.Navigation("ReservaDsses");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BedAndDrinks.Models.Servicio", b =>
                {
                    b.Navigation("PaqueteServicios");

                    b.Navigation("ReservaDsses");
                });

            modelBuilder.Entity("BedAndDrinks.Models.TipoHabitacion", b =>
                {
                    b.Navigation("TipoHabitacionPaquetes");
                });

            modelBuilder.Entity("BedAndDrinks.Models.TipoRol", b =>
                {
                    b.Navigation("PermisosTipoRols");

                    b.Navigation("Rols");
                });
#pragma warning restore 612, 618
        }
    }
}
